export const jobsData = {
    "jobs": [
        {
            "id": 1,
            "title": "Proqramçı",
            "description": "Yüksək keyfiyyətli proqram təminatları inkişaf etdirin. Müasir texnologiyalarla işləmək imkanı qazanın.",
            "location": "İstanbul",
            "experience": "3+ il",
            "postedDate": "01 Avqust 2024",
            "expiryDate": "31 Dekabr 2024",
            "icon": "fa-laptop-code",
            "salary": "15.000 TL",
            "company": "TechnoSoft",
            "requirements": "Magistr dərəcəsi, Python, JavaScript",
            "languages": "İngilis dili (Yaxşı səviyyədə)",
            "contact": "info@technosoft.com, +90 212 123 45 67",
            "workHours": "09:00 - 18:00",
            "days": "Bazar ertəsi - Cümə"
        },
        {
            "id": 2,
            "title": "Marketinq Mütəxəssisi",
            "description": "Şirkətimizin bazar payını artırmaq üçün strategiyalar inkişaf etdirin və tətbiq edin.",
            "location": "Ankara",
            "experience": "2+ il",
            "postedDate": "15 İyul 2024",
            "expiryDate": "30 Noyabr 2024",
            "icon": "fa-chart-line",
            "salary": "12.000 TL",
            "company": "MarketMakers",
            "requirements": "Bakalavr dərəcəsi, SEO, Google Analytics",
            "languages": "Türkcə (Ana dil), İngilis dili (Orta səviyyədə)",
            "contact": "hr@marketmakers.com, +90 312 234 56 78",
            "workHours": "10:00 - 19:00",
            "days": "Bazar ertəsi - Cümə"
        },
        {
            "id": 3,
            "title": "İnsan Resursları Mütəxəssisi",
            "description": "İşə qəbul proseslərini idarə edin və işçi məmnuniyyətini artırın.",
            "location": "İzmir",
            "experience": "5+ il",
            "postedDate": "01 İyul 2024",
            "expiryDate": "31 Oktyabr 2024",
            "icon": "fa-users",
            "salary": "18.000 TL",
            "company": "PeoplePlus",
            "requirements": "İK Bakalavr, İş Hüququ, İnsan Resursları İdarəetməsi",
            "languages": "Türkcə (Ana dil), İngilis dili (Yaxşı səviyyədə)",
            "contact": "contact@peopleplus.com, +90 232 345 67 89",
            "workHours": "08:00 - 17:00",
            "days": "Bazar ertəsi - Cümə"
        },
        {
            "id": 4,
            "title": "Veb Dizayner",
            "description": "Veb saytların vizual və funksional dizaynlarını inkişaf etdirin.",
            "location": "Bursa",
            "experience": "2+ il",
            "postedDate": "10 İyul 2024",
            "expiryDate": "15 Noyabr 2024",
            "icon": "fa-desktop",
            "salary": "14.000 TL",
            "company": "DesignLab",
            "requirements": "HTML, CSS, JavaScript, UX/UI",
            "languages": "Türkcə (Ana dil)",
            "contact": "info@designlab.com, +90 224 567 89 00",
            "workHours": "09:00 - 18:00",
            "days": "Bazar ertəsi - Cümə"
        },
        {
            "id": 5,
            "title": "Maliyyə Analitiki",
            "description": "Maliyyə analizləri apararaq şirkətin maliyyə strategiyalarını inkişaf etdirin.",
            "location": "Adana",
            "experience": "4+ il",
            "postedDate": "20 İyul 2024",
            "expiryDate": "20 Oktyabr 2024",
            "icon": "fa-calculator",
            "salary": "16.000 TL",
            "company": "FinWise",
            "requirements": "Maliyyə Bakalavr, Excel, Maliyyə Analizi",
            "languages": "Türkcə (Ana dil), İngilis dili (Yaxşı səviyyədə)",
            "contact": "hr@finwise.com, +90 322 678 90 12",
            "workHours": "09:00 - 18:00",
            "days": "Bazar ertəsi - Cümə"
        }
    ]
};
