export const jobsData = {
    "jobs": [
        {
            "id": 1,
            "title": "Yazılım Geliştirici",
            "description": "Yüksek kaliteli yazılım çözümleri geliştirin. Modern teknolojilerle çalışma fırsatını yakalayın.",
            "location": "İstanbul",
            "experience": "3+ yıl",
            "postedDate": "01 Ağustos 2024",
            "expiryDate": "31 Aralık 2024",
            "icon": "fa-laptop-code",
            "salary": "15.000 TL",
            "company": "TechnoSoft",
            "requirements": "Yüksek lisans, Python, JavaScript",
            "languages": "İngilizce (İyi seviyede)",
            "contact": "info@technosoft.com, +90 212 123 45 67",
            "workHours": "09:00 - 18:00",
            "days": "Pazartesi - Cuma"
        },
        {
            "id": 2,
            "title": "Pazarlama Uzmanı",
            "description": "Şirketimizin pazar payını artırmak için stratejiler geliştirin ve uygulayın.",
            "location": "Ankara",
            "experience": "2+ yıl",
            "postedDate": "15 Temmuz 2024",
            "expiryDate": "30 Kasım 2024",
            "icon": "fa-chart-line",
            "salary": "12.000 TL",
            "company": "MarketMakers",
            "requirements": "Lisans, SEO, Google Analytics",
            "languages": "Türkçe (Ana dil), İngilizce (Orta seviye)",
            "contact": "hr@marketmakers.com, +90 312 234 56 78",
            "workHours": "10:00 - 19:00",
            "days": "Pazartesi - Cuma"
        },
        {
            "id": 3,
            "title": "İnsan Kaynakları Uzmanı",
            "description": "İşe alım süreçlerini yönetin ve çalışan memnuniyetini artırın.",
            "location": "İzmir",
            "experience": "5+ yıl",
            "postedDate": "01 Temmuz 2024",
            "expiryDate": "31 Ekim 2024",
            "icon": "fa-users",
            "salary": "18.000 TL",
            "company": "PeoplePlus",
            "requirements": "İK Lisans, İş Hukuku, İnsan Kaynakları Yönetimi",
            "languages": "Türkçe (Ana dil), İngilizce (İyi seviyede)",
            "contact": "contact@peopleplus.com, +90 232 345 67 89",
            "workHours": "08:00 - 17:00",
            "days": "Pazartesi - Cuma"
        },
        {
            "id": 4,
            "title": "Web Tasarımcı",
            "description": "Web sitelerinin görsel ve işlevsel tasarımlarını geliştirin.",
            "location": "Bursa",
            "experience": "2+ yıl",
            "postedDate": "10 Temmuz 2024",
            "expiryDate": "15 Kasım 2024",
            "icon": "fa-desktop",
            "salary": "14.000 TL",
            "company": "DesignLab",
            "requirements": "HTML, CSS, JavaScript, UX/UI",
            "languages": "Türkçe (Ana dil)",
            "contact": "info@designlab.com, +90 224 567 89 00",
            "workHours": "09:00 - 18:00",
            "days": "Pazartesi - Cuma"
        },
        {
            "id": 5,
            "title": "Finans Analisti",
            "description": "Finansal analizler yaparak şirketin mali stratejilerini geliştirin.",
            "location": "Adana",
            "experience": "4+ yıl",
            "postedDate": "20 Temmuz 2024",
            "expiryDate": "20 Ekim 2024",
            "icon": "fa-calculator",
            "salary": "16.000 TL",
            "company": "FinWise",
            "requirements": "Finans Lisans, Excel, Finansal Analiz",
            "languages": "Türkçe (Ana dil), İngilizce (İyi seviyede)",
            "contact": "hr@finwise.com, +90 322 678 90 12",
            "workHours": "09:00 - 18:00",
            "days": "Pazartesi - Cuma"
        }
    ]
};